### ISSUE TITLE
You are retraining your NN with test data!!!

### ISSUE THREAD

**Issue by xuruiyang** [sebastianheinz/stockprediction#5]
In your implementation, you are retaining your model with test data! This should be strictly forbidden in any ML practice!

**Comment by sebastianheinz** [comment]
The model is trained only on the training partition X_train and y_train. Where exactly do you see a retraining on the test set?

**Comment by xuruiyang** [comment]
Sorry, I misunderstood some part of your code. It is perfectly fine.
